/*
 * Yodlee Core APIs
 * This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. You can generate a client SDK for Python, Java, JavaScript, PHP, or other languages according to your development needs. For more details about the APIs, refer to <a href=\"https://developer.envestnet.com/resources/yodlee/yodlee-api-overview/docs\">Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API's description.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: developer@yodlee.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Identifier} from './Identifier';
import {Name} from './Name';

/**
 * The AccountHolder model module.
 * @module model/AccountHolder
 * @version 1.1.0
 */
export class AccountHolder {
  /**
   * Constructs a new <code>AccountHolder</code>.
   * @alias module:model/AccountHolder
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AccountHolder</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AccountHolder} obj Optional instance to populate.
   * @return {module:model/AccountHolder} The populated <code>AccountHolder</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AccountHolder();
      if (data.hasOwnProperty('identifier'))
        obj.identifier = ApiClient.convertToType(data['identifier'], [Identifier]);
      if (data.hasOwnProperty('gender'))
        obj.gender = ApiClient.convertToType(data['gender'], 'String');
      if (data.hasOwnProperty('ownership'))
        obj.ownership = ApiClient.convertToType(data['ownership'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = Name.constructFromObject(data['name']);
    }
    return obj;
  }
}

/**
 * Identifiers of the account holder.<br><br><b>Aggregated / Manual</b>: Aggregated <br><b>Applicable containers</b>: bank<br><b>Endpoints</b>:<ul><li>GET accounts</li><li>GET accounts/{accountId}</li></ul>
 * @member {Array.<module:model/Identifier>} identifier
 */
AccountHolder.prototype.identifier = undefined;

/**
 * Identifiers of the account holder.<br><br><b>Aggregated / Manual</b>: Aggregated <br><b>Applicable containers</b>: bank<br><b>Endpoints</b>:<ul><li>GET accounts</li><li>GET accounts/{accountId}</li></ul>
 * @member {String} gender
 */
AccountHolder.prototype.gender = undefined;

/**
 * Allowed values for the <code>ownership</code> property.
 * @enum {String}
 * @readonly
 */
AccountHolder.OwnershipEnum = {
  /**
   * value: "PRIMARY"
   * @const
   */
  PRIMARY: "PRIMARY",

  /**
   * value: "SECONDARY"
   * @const
   */
  SECONDARY: "SECONDARY",

  /**
   * value: "CUSTODIAN"
   * @const
   */
  CUSTODIAN: "CUSTODIAN",

  /**
   * value: "OTHERS"
   * @const
   */
  OTHERS: "OTHERS",

  /**
   * value: "POWER_OF_ATTORNEY"
   * @const
   */
  POWER_OF_ATTORNEY: "POWER_OF_ATTORNEY",

  /**
   * value: "TRUSTEE"
   * @const
   */
  TRUSTEE: "TRUSTEE",

  /**
   * value: "JOINT_OWNER"
   * @const
   */
  JOINT_OWNER: "JOINT_OWNER",

  /**
   * value: "BENEFICIARY"
   * @const
   */
  BENEFICIARY: "BENEFICIARY",

  /**
   * value: "AAS"
   * @const
   */
  AAS: "AAS",

  /**
   * value: "BUSINESS"
   * @const
   */
  BUSINESS: "BUSINESS",

  /**
   * value: "DBA"
   * @const
   */
  DBA: "DBA",

  /**
   * value: "TRUST"
   * @const
   */
  TRUST: "TRUST"
};
/**
 * Indicates the ownership of the account.<br><br><b>Aggregated / Manual</b>: Aggregated <br><b>Applicable containers</b>: bank<br><b>Endpoints</b>:<ul><li>GET accounts</li><li>GET accounts/{accountId}</li></ul><b>Applicable Values</b><br>
 * @member {module:model/AccountHolder.OwnershipEnum} ownership
 */
AccountHolder.prototype.ownership = undefined;

/**
 * @member {module:model/Name} name
 */
AccountHolder.prototype.name = undefined;

