/*
 * Yodlee Core APIs
 * This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. You can generate a client SDK for Python, Java, JavaScript, PHP, or other languages according to your development needs. For more details about the APIs, refer to <a href=\"https://developer.envestnet.com/resources/yodlee/yodlee-api-overview/docs\">Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API's description.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: developer@yodlee.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ContainerAttributes} from './ContainerAttributes';

/**
 * The Attribute model module.
 * @module model/Attribute
 * @version 1.1.0
 */
export class Attribute {
  /**
   * Constructs a new <code>Attribute</code>.
   * @alias module:model/Attribute
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Attribute</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Attribute} obj Optional instance to populate.
   * @return {module:model/Attribute} The populated <code>Attribute</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Attribute();
      if (data.hasOwnProperty('container'))
        obj.container = ApiClient.convertToType(data['container'], ['String']);
      if (data.hasOwnProperty('fromDate'))
        obj.fromDate = ApiClient.convertToType(data['fromDate'], 'String');
      if (data.hasOwnProperty('toFinYear'))
        obj.toFinYear = ApiClient.convertToType(data['toFinYear'], 'String');
      if (data.hasOwnProperty('fromFinYear'))
        obj.fromFinYear = ApiClient.convertToType(data['fromFinYear'], 'String');
      if (data.hasOwnProperty('containerAttributes'))
        obj.containerAttributes = ContainerAttributes.constructFromObject(data['containerAttributes']);
      if (data.hasOwnProperty('toDate'))
        obj.toDate = ApiClient.convertToType(data['toDate'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>container</code> property.
 * @enum {String}
 * @readonly
 */
Attribute.ContainerEnum = {
  /**
   * value: "bank"
   * @const
   */
  bank: "bank",

  /**
   * value: "creditCard"
   * @const
   */
  creditCard: "creditCard",

  /**
   * value: "investment"
   * @const
   */
  investment: "investment",

  /**
   * value: "insurance"
   * @const
   */
  insurance: "insurance",

  /**
   * value: "loan"
   * @const
   */
  loan: "loan",

  /**
   * value: "reward"
   * @const
   */
  reward: "reward",

  /**
   * value: "bill"
   * @const
   */
  bill: "bill",

  /**
   * value: "realEstate"
   * @const
   */
  realEstate: "realEstate",

  /**
   * value: "otherAssets"
   * @const
   */
  otherAssets: "otherAssets",

  /**
   * value: "otherLiabilities"
   * @const
   */
  otherLiabilities: "otherLiabilities"
};
/**
 * Containers for which the attributes are supported.<br><br><b>Endpoints</b>:<ul><li>GET providers</li><li>GET providers/{providerId}</li></ul>
 * @member {Array.<module:model/Attribute.ContainerEnum>} container
 */
Attribute.prototype.container = undefined;

/**
 * Applicable only to EBILLS and STATEMENTS attributes of DOCUMENT dataset.<br><br><b>Endpoints</b>:<ul><li>POST providerAccounts</li><li>PUT providerAccounts</li></ul>
 * @member {String} fromDate
 */
Attribute.prototype.fromDate = undefined;

/**
 * Applicable only to TAX attribute of DOCUMENT dataset.<br><br><b>Endpoints</b>:<ul><li>POST providerAccounts</li><li>PUT providerAccounts</li></ul>
 * @member {String} toFinYear
 */
Attribute.prototype.toFinYear = undefined;

/**
 * Applicable only to TAX attribute of DOCUMENT dataset.<br><br><b>Endpoints</b>:<ul><li>POST providerAccounts</li><li>PUT providerAccounts</li></ul>
 * @member {String} fromFinYear
 */
Attribute.prototype.fromFinYear = undefined;

/**
 * @member {module:model/ContainerAttributes} containerAttributes
 */
Attribute.prototype.containerAttributes = undefined;

/**
 * Applicable only to EBILLS and STATEMENTS attributes of DOCUMENT dataset.<br><br><b>Endpoints</b>:<ul><li>POST providerAccounts</li><li>PUT providerAccounts</li></ul>
 * @member {String} toDate
 */
Attribute.prototype.toDate = undefined;

/**
 * Allowed values for the <code>name</code> property.
 * @enum {String}
 * @readonly
 */
Attribute.NameEnum = {
  /**
   * value: "BASIC_ACCOUNT_INFO"
   * @const
   */
  BASIC_ACCOUNT_INFO: "BASIC_ACCOUNT_INFO",

  /**
   * value: "TRANSACTIONS"
   * @const
   */
  TRANSACTIONS: "TRANSACTIONS",

  /**
   * value: "STATEMENTS"
   * @const
   */
  STATEMENTS: "STATEMENTS",

  /**
   * value: "HOLDINGS"
   * @const
   */
  HOLDINGS: "HOLDINGS",

  /**
   * value: "ACCOUNT_DETAILS"
   * @const
   */
  ACCOUNT_DETAILS: "ACCOUNT_DETAILS",

  /**
   * value: "TAX"
   * @const
   */
  TAX: "TAX",

  /**
   * value: "EBILLS"
   * @const
   */
  EBILLS: "EBILLS",

  /**
   * value: "FULL_ACCT_NUMBER"
   * @const
   */
  FULL_ACCT_NUMBER: "FULL_ACCT_NUMBER",

  /**
   * value: "BANK_TRANSFER_CODE"
   * @const
   */
  BANK_TRANSFER_CODE: "BANK_TRANSFER_CODE",

  /**
   * value: "HOLDER_NAME"
   * @const
   */
  HOLDER_NAME: "HOLDER_NAME",

  /**
   * value: "HOLDER_DETAILS"
   * @const
   */
  HOLDER_DETAILS: "HOLDER_DETAILS",

  /**
   * value: "PAYMENT_PROFILE"
   * @const
   */
  PAYMENT_PROFILE: "PAYMENT_PROFILE",

  /**
   * value: "PAYMENT_DETAILS"
   * @const
   */
  PAYMENT_DETAILS: "PAYMENT_DETAILS",

  /**
   * value: "INTEREST_DETAILS"
   * @const
   */
  INTEREST_DETAILS: "INTEREST_DETAILS",

  /**
   * value: "COVERAGE"
   * @const
   */
  COVERAGE: "COVERAGE"
};
/**
 * Attributes that are supported for a dataset.<br><br><b>Endpoints</b>:<ul><li>GET providers</li><li>GET providers/{providerId}</li></ul>
 * @member {module:model/Attribute.NameEnum} name
 */
Attribute.prototype.name = undefined;

