/*
 * Yodlee Core APIs
 * This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. You can generate a client SDK for Python, Java, JavaScript, PHP, or other languages according to your development needs. For more details about the APIs, refer to <a href=\"https://developer.envestnet.com/resources/yodlee/yodlee-api-overview/docs\">Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API's description.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: developer@yodlee.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CobrandPublicKeyResponse model module.
 * @module model/CobrandPublicKeyResponse
 * @version 1.1.0
 */
export class CobrandPublicKeyResponse {
  /**
   * Constructs a new <code>CobrandPublicKeyResponse</code>.
   * @alias module:model/CobrandPublicKeyResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CobrandPublicKeyResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CobrandPublicKeyResponse} obj Optional instance to populate.
   * @return {module:model/CobrandPublicKeyResponse} The populated <code>CobrandPublicKeyResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CobrandPublicKeyResponse();
      if (data.hasOwnProperty('keyAlias'))
        obj.keyAlias = ApiClient.convertToType(data['keyAlias'], 'String');
      if (data.hasOwnProperty('keyAsPemString'))
        obj.keyAsPemString = ApiClient.convertToType(data['keyAsPemString'], 'String');
    }
    return obj;
  }
}

/**
 * The key name used for encryption.<br><br><b>Endpoints</b>:<ul><li>GET cobrand/publicKey</li></ul>
 * @member {String} keyAlias
 */
CobrandPublicKeyResponse.prototype.keyAlias = undefined;

/**
 * Public key that the customer should be using to encrypt the credentials and answers before sending to the add & update providerAccounts APIs.<br><br><b>Endpoints</b>:<ul><li>GET cobrand/publicKey</li></ul>
 * @member {String} keyAsPemString
 */
CobrandPublicKeyResponse.prototype.keyAsPemString = undefined;

