/*
 * Yodlee Core APIs
 * This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. You can generate a client SDK for Python, Java, JavaScript, PHP, or other languages according to your development needs. For more details about the APIs, refer to <a href=\"https://developer.envestnet.com/resources/yodlee/yodlee-api-overview/docs\">Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API's description.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: developer@yodlee.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {DerivedHolding} from './DerivedHolding';
import {DerivedHoldingsAccount} from './DerivedHoldingsAccount';
import {Money} from './Money';

/**
 * The DerivedHoldingsSummary model module.
 * @module model/DerivedHoldingsSummary
 * @version 1.1.0
 */
export class DerivedHoldingsSummary {
  /**
   * Constructs a new <code>DerivedHoldingsSummary</code>.
   * @alias module:model/DerivedHoldingsSummary
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DerivedHoldingsSummary</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DerivedHoldingsSummary} obj Optional instance to populate.
   * @return {module:model/DerivedHoldingsSummary} The populated <code>DerivedHoldingsSummary</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DerivedHoldingsSummary();
      if (data.hasOwnProperty('holding'))
        obj.holding = ApiClient.convertToType(data['holding'], [DerivedHolding]);
      if (data.hasOwnProperty('classificationType'))
        obj.classificationType = ApiClient.convertToType(data['classificationType'], 'String');
      if (data.hasOwnProperty('classificationValue'))
        obj.classificationValue = ApiClient.convertToType(data['classificationValue'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = Money.constructFromObject(data['value']);
      if (data.hasOwnProperty('account'))
        obj.account = ApiClient.convertToType(data['account'], [DerivedHoldingsAccount]);
    }
    return obj;
  }
}

/**
 * Securities that belong to the asset classification type and contributed to the summary value.<br><b>Required Feature Enablement</b>: Asset classification feature.<br><br><b>Applicable containers</b>: investment, insurance<br>
 * @member {Array.<module:model/DerivedHolding>} holding
 */
DerivedHoldingsSummary.prototype.holding = undefined;

/**
 * The classification type of the security. The supported asset classification type and the values are provided in the /holdings/assetClassificationList.<br><b>Required Feature Enablement</b>: Asset classification feature.<br><br><b>Applicable containers</b>: investment, insurance<br>
 * @member {String} classificationType
 */
DerivedHoldingsSummary.prototype.classificationType = undefined;

/**
 * The classification value that corresponds to the classification type of the holding. The supported asset classification type and the values are provided in the /holdings/assetClassificationList.<br><b>Required Feature Enablement</b>: Asset classification feature.<br><br><b>Applicable containers</b>: investment, insurance<br>
 * @member {String} classificationValue
 */
DerivedHoldingsSummary.prototype.classificationValue = undefined;

/**
 * @member {module:model/Money} value
 */
DerivedHoldingsSummary.prototype.value = undefined;

/**
 * Accounts that contribute to the classification. <br><b>Required Feature Enablement</b>: Asset classification feature.<br><br><b>Applicable containers</b>: investment, insurance<br>
 * @member {Array.<module:model/DerivedHoldingsAccount>} account
 */
DerivedHoldingsSummary.prototype.account = undefined;

