/*
 * Yodlee Core APIs
 * This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. You can generate a client SDK for Python, Java, JavaScript, PHP, or other languages according to your development needs. For more details about the APIs, refer to <a href=\"https://developer.envestnet.com/resources/yodlee/yodlee-api-overview/docs\">Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API's description.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: developer@yodlee.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Attribute} from './Attribute';

/**
 * The ProvidersDataset model module.
 * @module model/ProvidersDataset
 * @version 1.1.0
 */
export class ProvidersDataset {
  /**
   * Constructs a new <code>ProvidersDataset</code>.
   * @alias module:model/ProvidersDataset
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ProvidersDataset</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProvidersDataset} obj Optional instance to populate.
   * @return {module:model/ProvidersDataset} The populated <code>ProvidersDataset</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProvidersDataset();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('attribute'))
        obj.attribute = ApiClient.convertToType(data['attribute'], [Attribute]);
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>name</code> property.
 * @enum {String}
 * @readonly
 */
ProvidersDataset.NameEnum = {
  /**
   * value: "BASIC_AGG_DATA"
   * @const
   */
  BASIC_AGG_DATA: "BASIC_AGG_DATA",

  /**
   * value: "ADVANCE_AGG_DATA"
   * @const
   */
  ADVANCE_AGG_DATA: "ADVANCE_AGG_DATA",

  /**
   * value: "ACCT_PROFILE"
   * @const
   */
  ACCT_PROFILE: "ACCT_PROFILE",

  /**
   * value: "DOCUMENT"
   * @const
   */
  DOCUMENT: "DOCUMENT"
};
/**
 * The name of the dataset requested from the provider site<br><br><b>Account Type</b>: Manual<br><b>Endpoints</b>:<ul><li>GET accounts</li><li>GET accounts/{accountId}</li><li>GET providerAccounts</li><li>POST providerAccounts</li><li>PUT providerAccounts/{providerAccountId}</li><li>GET providerAccounts/{providerAccountId}</li><li>GET providers/{providerId}</li><li>GET providers</li></ul><b>Applicable Values</b><br>
 * @member {module:model/ProvidersDataset.NameEnum} name
 */
ProvidersDataset.prototype.name = undefined;

/**
 * The name of the dataset attribute suported by the provider.<br><br><b>Endpoints</b>:<ul><li>GET providers/{providerId}</li><li>GET providers</li></ul>
 * @member {Array.<module:model/Attribute>} attribute
 */
ProvidersDataset.prototype.attribute = undefined;

