/*
 * Yodlee Core APIs
 * This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. You can generate a client SDK for Python, Java, JavaScript, PHP, or other languages according to your development needs. For more details about the APIs, refer to <a href=\"https://developer.envestnet.com/resources/yodlee/yodlee-api-overview/docs\">Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API's description.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: developer@yodlee.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RewardBalance model module.
 * @module model/RewardBalance
 * @version 1.1.0
 */
export class RewardBalance {
  /**
   * Constructs a new <code>RewardBalance</code>.
   * @alias module:model/RewardBalance
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RewardBalance</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RewardBalance} obj Optional instance to populate.
   * @return {module:model/RewardBalance} The populated <code>RewardBalance</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RewardBalance();
      if (data.hasOwnProperty('expiryDate'))
        obj.expiryDate = ApiClient.convertToType(data['expiryDate'], 'String');
      if (data.hasOwnProperty('balanceToReward'))
        obj.balanceToReward = ApiClient.convertToType(data['balanceToReward'], 'String');
      if (data.hasOwnProperty('balanceType'))
        obj.balanceType = ApiClient.convertToType(data['balanceType'], 'String');
      if (data.hasOwnProperty('balance'))
        obj.balance = ApiClient.convertToType(data['balance'], 'Number');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('balanceToLevel'))
        obj.balanceToLevel = ApiClient.convertToType(data['balanceToLevel'], 'String');
      if (data.hasOwnProperty('units'))
        obj.units = ApiClient.convertToType(data['units'], 'String');
    }
    return obj;
  }
}

/**
 * The date on which the balance expires.<br><br><b>Account Type</b>: Aggregated<br><b>Applicable containers</b>: reward<br><b>Endpoints</b>:<ul><li>GET accounts</li><li>GET accounts/{accountId}</li><li>GET dataExtracts/userData</li></ul>
 * @member {String} expiryDate
 */
RewardBalance.prototype.expiryDate = undefined;

/**
 * The balance required to qualify for a reward such as retaining membership, business reward, etc.<br><br><b>Account Type</b>: Aggregated<br><b>Applicable containers</b>: reward<br><b>Endpoints</b>:<ul><li>GET accounts</li><li>GET accounts/{accountId}</li><li>GET dataExtracts/userData</li></ul>
 * @member {String} balanceToReward
 */
RewardBalance.prototype.balanceToReward = undefined;

/**
 * Allowed values for the <code>balanceType</code> property.
 * @enum {String}
 * @readonly
 */
RewardBalance.BalanceTypeEnum = {
  /**
   * value: "EXPIRING_BALANCE"
   * @const
   */
  EXPIRING_BALANCE: "EXPIRING_BALANCE",

  /**
   * value: "BALANCE_TO_LEVEL"
   * @const
   */
  BALANCE_TO_LEVEL: "BALANCE_TO_LEVEL",

  /**
   * value: "BALANCE_TO_REWARD"
   * @const
   */
  BALANCE_TO_REWARD: "BALANCE_TO_REWARD",

  /**
   * value: "BALANCE"
   * @const
   */
  BALANCE: "BALANCE",

  /**
   * value: "TOTAL_BALANCE"
   * @const
   */
  TOTAL_BALANCE: "TOTAL_BALANCE"
};
/**
 * The type of reward balance.<br><br><b>Account Type</b>: Aggregated<br><b>Applicable containers</b>: reward<br><b>Endpoints</b>:<ul><li>GET accounts</li><li>GET accounts/{accountId}</li><li>GET dataExtracts/userData</li></ul><b>Applicable Values</b><br>
 * @member {module:model/RewardBalance.BalanceTypeEnum} balanceType
 */
RewardBalance.prototype.balanceType = undefined;

/**
 * The actual reward balance.<br><br><b>Account Type</b>: Aggregated<br><b>Applicable containers</b>: reward<br><b>Endpoints</b>:<ul><li>GET accounts</li><li>GET accounts/{accountId}</li><li>GET dataExtracts/userData</li></ul>
 * @member {Number} balance
 */
RewardBalance.prototype.balance = undefined;

/**
 * The description for the reward balance as available at provider source.<br><br><b>Account Type</b>: Aggregated<br><b>Applicable containers</b>: reward<br><b>Endpoints</b>:<ul><li>GET accounts</li><li>GET accounts/{accountId}</li><li>GET dataExtracts/userData</li></ul>
 * @member {String} description
 */
RewardBalance.prototype.description = undefined;

/**
 * The balance required to reach a reward level.<br><br><b>Account Type</b>: Aggregated<br><b>Applicable containers</b>: reward<br><b>Endpoints</b>:<ul><li>GET accounts</li><li>GET accounts/{accountId}</li><li>GET dataExtracts/userData</li></ul>
 * @member {String} balanceToLevel
 */
RewardBalance.prototype.balanceToLevel = undefined;

/**
 * Unit of reward balance - miles, points, segments, dollars, credits.<br><br><b>Account Type</b>: Aggregated<br><b>Applicable containers</b>: reward<br><b>Endpoints</b>:<ul><li>GET accounts</li><li>GET accounts/{accountId}</li><li>GET dataExtracts/userData</li></ul>
 * @member {String} units
 */
RewardBalance.prototype.units = undefined;

