/*
 * Yodlee Core APIs
 * This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. You can generate a client SDK for Python, Java, JavaScript, PHP, or other languages according to your development needs. For more details about the APIs, refer to <a href=\"https://developer.envestnet.com/resources/yodlee/yodlee-api-overview/docs\">Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API's description.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: developer@yodlee.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RuleClause model module.
 * @module model/RuleClause
 * @version 1.1.0
 */
export class RuleClause {
  /**
   * Constructs a new <code>RuleClause</code>.
   * @alias module:model/RuleClause
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RuleClause</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RuleClause} obj Optional instance to populate.
   * @return {module:model/RuleClause} The populated <code>RuleClause</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RuleClause();
      if (data.hasOwnProperty('field'))
        obj.field = ApiClient.convertToType(data['field'], 'String');
      if (data.hasOwnProperty('userDefinedRuleId'))
        obj.userDefinedRuleId = ApiClient.convertToType(data['userDefinedRuleId'], 'Number');
      if (data.hasOwnProperty('fieldValue'))
        obj.fieldValue = ApiClient.convertToType(data['fieldValue'], 'String');
      if (data.hasOwnProperty('operation'))
        obj.operation = ApiClient.convertToType(data['operation'], 'String');
      if (data.hasOwnProperty('ruleClauseId'))
        obj.ruleClauseId = ApiClient.convertToType(data['ruleClauseId'], 'Number');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>field</code> property.
 * @enum {String}
 * @readonly
 */
RuleClause.FieldEnum = {
  /**
   * value: "amount"
   * @const
   */
  amount: "amount",

  /**
   * value: "description"
   * @const
   */
  description: "description"
};
/**
 * Field for which the clause is created.<br><br><br><b>Valid Values</b>:amount,description<b>Applicable containers</b>: creditCard, investment, insurance, loan<br>
 * @member {module:model/RuleClause.FieldEnum} field
 */
RuleClause.prototype.field = undefined;

/**
 * Unique identifier generated for every rule the user creates.<br><br><b>Applicable containers</b>: creditCard, investment, insurance, loan<br>
 * @member {Number} userDefinedRuleId
 */
RuleClause.prototype.userDefinedRuleId = undefined;

/**
 * The value would be the amount value in case of amount based rule clause or the string value in case of description based rule clause.<br><br><b>Applicable containers</b>: creditCard, investment, insurance, loan<br>
 * @member {String} fieldValue
 */
RuleClause.prototype.fieldValue = undefined;

/**
 * Allowed values for the <code>operation</code> property.
 * @enum {String}
 * @readonly
 */
RuleClause.OperationEnum = {
  /**
   * value: "numberEquals"
   * @const
   */
  numberEquals: "numberEquals",

  /**
   * value: "numberLessThan"
   * @const
   */
  numberLessThan: "numberLessThan",

  /**
   * value: "numberLessThanEquals"
   * @const
   */
  numberLessThanEquals: "numberLessThanEquals",

  /**
   * value: "numberGreaterThan"
   * @const
   */
  numberGreaterThan: "numberGreaterThan",

  /**
   * value: "numberGreaterThanEquals"
   * @const
   */
  numberGreaterThanEquals: "numberGreaterThanEquals",

  /**
   * value: "stringEquals"
   * @const
   */
  stringEquals: "stringEquals",

  /**
   * value: "stringContains"
   * @const
   */
  stringContains: "stringContains"
};
/**
 * Operation for which the clause is created.<br><br><b>Applicable containers</b>: creditCard, investment, insurance, loan<br>
 * @member {module:model/RuleClause.OperationEnum} operation
 */
RuleClause.prototype.operation = undefined;

/**
 * Unique identifier generated for the rule clause.<br><br><b>Applicable containers</b>: creditCard, investment, insurance, loan<br>
 * @member {Number} ruleClauseId
 */
RuleClause.prototype.ruleClauseId = undefined;

