/* 
 * Yodlee Core APIs
 *
 * This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. You can generate a client SDK for Python, Java, JavaScript, PHP, or other languages according to your development needs. For more details about the APIs, refer to <a href=\"https://developer.envestnet.com/resources/yodlee/yodlee-api-overview/docs\">Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API's description.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: developer@yodlee.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Account
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccountTests
    {
        // TODO uncomment below to declare an instance variable for Account
        //private Account instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Account
            //instance = new Account();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Account
        /// </summary>
        [Test]
        public void AccountInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Account
            //Assert.IsInstanceOfType<Account> (instance, "variable 'instance' is a Account");
        }


        /// <summary>
        /// Test the property 'AvailableCash'
        /// </summary>
        [Test]
        public void AvailableCashTest()
        {
            // TODO unit test for the property 'AvailableCash'
        }
        /// <summary>
        /// Test the property 'IncludeInNetWorth'
        /// </summary>
        [Test]
        public void IncludeInNetWorthTest()
        {
            // TODO unit test for the property 'IncludeInNetWorth'
        }
        /// <summary>
        /// Test the property 'MoneyMarketBalance'
        /// </summary>
        [Test]
        public void MoneyMarketBalanceTest()
        {
            // TODO unit test for the property 'MoneyMarketBalance'
        }
        /// <summary>
        /// Test the property 'EnrollmentDate'
        /// </summary>
        [Test]
        public void EnrollmentDateTest()
        {
            // TODO unit test for the property 'EnrollmentDate'
        }
        /// <summary>
        /// Test the property 'EstimatedDate'
        /// </summary>
        [Test]
        public void EstimatedDateTest()
        {
            // TODO unit test for the property 'EstimatedDate'
        }
        /// <summary>
        /// Test the property 'Memo'
        /// </summary>
        [Test]
        public void MemoTest()
        {
            // TODO unit test for the property 'Memo'
        }
        /// <summary>
        /// Test the property 'Guarantor'
        /// </summary>
        [Test]
        public void GuarantorTest()
        {
            // TODO unit test for the property 'Guarantor'
        }
        /// <summary>
        /// Test the property 'InterestPaidLastYear'
        /// </summary>
        [Test]
        public void InterestPaidLastYearTest()
        {
            // TODO unit test for the property 'InterestPaidLastYear'
        }
        /// <summary>
        /// Test the property 'LastUpdated'
        /// </summary>
        [Test]
        public void LastUpdatedTest()
        {
            // TODO unit test for the property 'LastUpdated'
        }
        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Test]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }
        /// <summary>
        /// Test the property 'HomeInsuranceType'
        /// </summary>
        [Test]
        public void HomeInsuranceTypeTest()
        {
            // TODO unit test for the property 'HomeInsuranceType'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Cash'
        /// </summary>
        [Test]
        public void CashTest()
        {
            // TODO unit test for the property 'Cash'
        }
        /// <summary>
        /// Test the property 'TotalCreditLine'
        /// </summary>
        [Test]
        public void TotalCreditLineTest()
        {
            // TODO unit test for the property 'TotalCreditLine'
        }
        /// <summary>
        /// Test the property 'ProviderName'
        /// </summary>
        [Test]
        public void ProviderNameTest()
        {
            // TODO unit test for the property 'ProviderName'
        }
        /// <summary>
        /// Test the property 'ValuationType'
        /// </summary>
        [Test]
        public void ValuationTypeTest()
        {
            // TODO unit test for the property 'ValuationType'
        }
        /// <summary>
        /// Test the property 'MarginBalance'
        /// </summary>
        [Test]
        public void MarginBalanceTest()
        {
            // TODO unit test for the property 'MarginBalance'
        }
        /// <summary>
        /// Test the property 'Apr'
        /// </summary>
        [Test]
        public void AprTest()
        {
            // TODO unit test for the property 'Apr'
        }
        /// <summary>
        /// Test the property 'AvailableCredit'
        /// </summary>
        [Test]
        public void AvailableCreditTest()
        {
            // TODO unit test for the property 'AvailableCredit'
        }
        /// <summary>
        /// Test the property 'CurrentBalance'
        /// </summary>
        [Test]
        public void CurrentBalanceTest()
        {
            // TODO unit test for the property 'CurrentBalance'
        }
        /// <summary>
        /// Test the property 'IsManual'
        /// </summary>
        [Test]
        public void IsManualTest()
        {
            // TODO unit test for the property 'IsManual'
        }
        /// <summary>
        /// Test the property 'Profile'
        /// </summary>
        [Test]
        public void ProfileTest()
        {
            // TODO unit test for the property 'Profile'
        }
        /// <summary>
        /// Test the property 'EscrowBalance'
        /// </summary>
        [Test]
        public void EscrowBalanceTest()
        {
            // TODO unit test for the property 'EscrowBalance'
        }
        /// <summary>
        /// Test the property 'NextLevel'
        /// </summary>
        [Test]
        public void NextLevelTest()
        {
            // TODO unit test for the property 'NextLevel'
        }
        /// <summary>
        /// Test the property 'Classification'
        /// </summary>
        [Test]
        public void ClassificationTest()
        {
            // TODO unit test for the property 'Classification'
        }
        /// <summary>
        /// Test the property 'LoanPayoffAmount'
        /// </summary>
        [Test]
        public void LoanPayoffAmountTest()
        {
            // TODO unit test for the property 'LoanPayoffAmount'
        }
        /// <summary>
        /// Test the property 'InterestRateType'
        /// </summary>
        [Test]
        public void InterestRateTypeTest()
        {
            // TODO unit test for the property 'InterestRateType'
        }
        /// <summary>
        /// Test the property 'LoanPayByDate'
        /// </summary>
        [Test]
        public void LoanPayByDateTest()
        {
            // TODO unit test for the property 'LoanPayByDate'
        }
        /// <summary>
        /// Test the property 'FaceAmount'
        /// </summary>
        [Test]
        public void FaceAmountTest()
        {
            // TODO unit test for the property 'FaceAmount'
        }
        /// <summary>
        /// Test the property 'PolicyFromDate'
        /// </summary>
        [Test]
        public void PolicyFromDateTest()
        {
            // TODO unit test for the property 'PolicyFromDate'
        }
        /// <summary>
        /// Test the property 'PremiumPaymentTerm'
        /// </summary>
        [Test]
        public void PremiumPaymentTermTest()
        {
            // TODO unit test for the property 'PremiumPaymentTerm'
        }
        /// <summary>
        /// Test the property 'PolicyTerm'
        /// </summary>
        [Test]
        public void PolicyTermTest()
        {
            // TODO unit test for the property 'PolicyTerm'
        }
        /// <summary>
        /// Test the property 'RepaymentPlanType'
        /// </summary>
        [Test]
        public void RepaymentPlanTypeTest()
        {
            // TODO unit test for the property 'RepaymentPlanType'
        }
        /// <summary>
        /// Test the property 'AggregatedAccountType'
        /// </summary>
        [Test]
        public void AggregatedAccountTypeTest()
        {
            // TODO unit test for the property 'AggregatedAccountType'
        }
        /// <summary>
        /// Test the property 'AvailableBalance'
        /// </summary>
        [Test]
        public void AvailableBalanceTest()
        {
            // TODO unit test for the property 'AvailableBalance'
        }
        /// <summary>
        /// Test the property 'AccountStatus'
        /// </summary>
        [Test]
        public void AccountStatusTest()
        {
            // TODO unit test for the property 'AccountStatus'
        }
        /// <summary>
        /// Test the property 'LifeInsuranceType'
        /// </summary>
        [Test]
        public void LifeInsuranceTypeTest()
        {
            // TODO unit test for the property 'LifeInsuranceType'
        }
        /// <summary>
        /// Test the property 'FullAccountNumber'
        /// </summary>
        [Test]
        public void FullAccountNumberTest()
        {
            // TODO unit test for the property 'FullAccountNumber'
        }
        /// <summary>
        /// Test the property 'Premium'
        /// </summary>
        [Test]
        public void PremiumTest()
        {
            // TODO unit test for the property 'Premium'
        }
        /// <summary>
        /// Test the property 'AggregationSource'
        /// </summary>
        [Test]
        public void AggregationSourceTest()
        {
            // TODO unit test for the property 'AggregationSource'
        }
        /// <summary>
        /// Test the property 'OverDraftLimit'
        /// </summary>
        [Test]
        public void OverDraftLimitTest()
        {
            // TODO unit test for the property 'OverDraftLimit'
        }
        /// <summary>
        /// Test the property 'Nickname'
        /// </summary>
        [Test]
        public void NicknameTest()
        {
            // TODO unit test for the property 'Nickname'
        }
        /// <summary>
        /// Test the property 'Term'
        /// </summary>
        [Test]
        public void TermTest()
        {
            // TODO unit test for the property 'Term'
        }
        /// <summary>
        /// Test the property 'InterestRate'
        /// </summary>
        [Test]
        public void InterestRateTest()
        {
            // TODO unit test for the property 'InterestRate'
        }
        /// <summary>
        /// Test the property 'DeathBenefit'
        /// </summary>
        [Test]
        public void DeathBenefitTest()
        {
            // TODO unit test for the property 'DeathBenefit'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'CashValue'
        /// </summary>
        [Test]
        public void CashValueTest()
        {
            // TODO unit test for the property 'CashValue'
        }
        /// <summary>
        /// Test the property 'Holder'
        /// </summary>
        [Test]
        public void HolderTest()
        {
            // TODO unit test for the property 'Holder'
        }
        /// <summary>
        /// Test the property '_401kLoan'
        /// </summary>
        [Test]
        public void _401kLoanTest()
        {
            // TODO unit test for the property '_401kLoan'
        }
        /// <summary>
        /// Test the property 'HomeValue'
        /// </summary>
        [Test]
        public void HomeValueTest()
        {
            // TODO unit test for the property 'HomeValue'
        }
        /// <summary>
        /// Test the property 'AccountNumber'
        /// </summary>
        [Test]
        public void AccountNumberTest()
        {
            // TODO unit test for the property 'AccountNumber'
        }
        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Test]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }
        /// <summary>
        /// Test the property 'InterestPaidYTD'
        /// </summary>
        [Test]
        public void InterestPaidYTDTest()
        {
            // TODO unit test for the property 'InterestPaidYTD'
        }
        /// <summary>
        /// Test the property 'ProviderAccountId'
        /// </summary>
        [Test]
        public void ProviderAccountIdTest()
        {
            // TODO unit test for the property 'ProviderAccountId'
        }
        /// <summary>
        /// Test the property 'Collateral'
        /// </summary>
        [Test]
        public void CollateralTest()
        {
            // TODO unit test for the property 'Collateral'
        }
        /// <summary>
        /// Test the property 'Dataset'
        /// </summary>
        [Test]
        public void DatasetTest()
        {
            // TODO unit test for the property 'Dataset'
        }
        /// <summary>
        /// Test the property 'RunningBalance'
        /// </summary>
        [Test]
        public void RunningBalanceTest()
        {
            // TODO unit test for the property 'RunningBalance'
        }
        /// <summary>
        /// Test the property 'SourceId'
        /// </summary>
        [Test]
        public void SourceIdTest()
        {
            // TODO unit test for the property 'SourceId'
        }
        /// <summary>
        /// Test the property 'DueDate'
        /// </summary>
        [Test]
        public void DueDateTest()
        {
            // TODO unit test for the property 'DueDate'
        }
        /// <summary>
        /// Test the property 'Frequency'
        /// </summary>
        [Test]
        public void FrequencyTest()
        {
            // TODO unit test for the property 'Frequency'
        }
        /// <summary>
        /// Test the property 'MaturityAmount'
        /// </summary>
        [Test]
        public void MaturityAmountTest()
        {
            // TODO unit test for the property 'MaturityAmount'
        }
        /// <summary>
        /// Test the property 'AssociatedProviderAccountId'
        /// </summary>
        [Test]
        public void AssociatedProviderAccountIdTest()
        {
            // TODO unit test for the property 'AssociatedProviderAccountId'
        }
        /// <summary>
        /// Test the property 'IsAsset'
        /// </summary>
        [Test]
        public void IsAssetTest()
        {
            // TODO unit test for the property 'IsAsset'
        }
        /// <summary>
        /// Test the property 'PrincipalBalance'
        /// </summary>
        [Test]
        public void PrincipalBalanceTest()
        {
            // TODO unit test for the property 'PrincipalBalance'
        }
        /// <summary>
        /// Test the property 'TotalCashLimit'
        /// </summary>
        [Test]
        public void TotalCashLimitTest()
        {
            // TODO unit test for the property 'TotalCashLimit'
        }
        /// <summary>
        /// Test the property 'MaturityDate'
        /// </summary>
        [Test]
        public void MaturityDateTest()
        {
            // TODO unit test for the property 'MaturityDate'
        }
        /// <summary>
        /// Test the property 'MinimumAmountDue'
        /// </summary>
        [Test]
        public void MinimumAmountDueTest()
        {
            // TODO unit test for the property 'MinimumAmountDue'
        }
        /// <summary>
        /// Test the property 'AnnualPercentageYield'
        /// </summary>
        [Test]
        public void AnnualPercentageYieldTest()
        {
            // TODO unit test for the property 'AnnualPercentageYield'
        }
        /// <summary>
        /// Test the property 'AccountType'
        /// </summary>
        [Test]
        public void AccountTypeTest()
        {
            // TODO unit test for the property 'AccountType'
        }
        /// <summary>
        /// Test the property 'OriginationDate'
        /// </summary>
        [Test]
        public void OriginationDateTest()
        {
            // TODO unit test for the property 'OriginationDate'
        }
        /// <summary>
        /// Test the property 'TotalVestedBalance'
        /// </summary>
        [Test]
        public void TotalVestedBalanceTest()
        {
            // TODO unit test for the property 'TotalVestedBalance'
        }
        /// <summary>
        /// Test the property 'RewardBalance'
        /// </summary>
        [Test]
        public void RewardBalanceTest()
        {
            // TODO unit test for the property 'RewardBalance'
        }
        /// <summary>
        /// Test the property 'SourceAccountStatus'
        /// </summary>
        [Test]
        public void SourceAccountStatusTest()
        {
            // TODO unit test for the property 'SourceAccountStatus'
        }
        /// <summary>
        /// Test the property 'LinkedAccountIds'
        /// </summary>
        [Test]
        public void LinkedAccountIdsTest()
        {
            // TODO unit test for the property 'LinkedAccountIds'
        }
        /// <summary>
        /// Test the property 'DerivedApr'
        /// </summary>
        [Test]
        public void DerivedAprTest()
        {
            // TODO unit test for the property 'DerivedApr'
        }
        /// <summary>
        /// Test the property 'PolicyEffectiveDate'
        /// </summary>
        [Test]
        public void PolicyEffectiveDateTest()
        {
            // TODO unit test for the property 'PolicyEffectiveDate'
        }
        /// <summary>
        /// Test the property 'TotalUnvestedBalance'
        /// </summary>
        [Test]
        public void TotalUnvestedBalanceTest()
        {
            // TODO unit test for the property 'TotalUnvestedBalance'
        }
        /// <summary>
        /// Test the property 'AnnuityBalance'
        /// </summary>
        [Test]
        public void AnnuityBalanceTest()
        {
            // TODO unit test for the property 'AnnuityBalance'
        }
        /// <summary>
        /// Test the property 'AccountName'
        /// </summary>
        [Test]
        public void AccountNameTest()
        {
            // TODO unit test for the property 'AccountName'
        }
        /// <summary>
        /// Test the property 'TotalCreditLimit'
        /// </summary>
        [Test]
        public void TotalCreditLimitTest()
        {
            // TODO unit test for the property 'TotalCreditLimit'
        }
        /// <summary>
        /// Test the property 'PolicyStatus'
        /// </summary>
        [Test]
        public void PolicyStatusTest()
        {
            // TODO unit test for the property 'PolicyStatus'
        }
        /// <summary>
        /// Test the property 'ShortBalance'
        /// </summary>
        [Test]
        public void ShortBalanceTest()
        {
            // TODO unit test for the property 'ShortBalance'
        }
        /// <summary>
        /// Test the property 'Lender'
        /// </summary>
        [Test]
        public void LenderTest()
        {
            // TODO unit test for the property 'Lender'
        }
        /// <summary>
        /// Test the property 'LastEmployeeContributionAmount'
        /// </summary>
        [Test]
        public void LastEmployeeContributionAmountTest()
        {
            // TODO unit test for the property 'LastEmployeeContributionAmount'
        }
        /// <summary>
        /// Test the property 'ProviderId'
        /// </summary>
        [Test]
        public void ProviderIdTest()
        {
            // TODO unit test for the property 'ProviderId'
        }
        /// <summary>
        /// Test the property 'LastPaymentDate'
        /// </summary>
        [Test]
        public void LastPaymentDateTest()
        {
            // TODO unit test for the property 'LastPaymentDate'
        }
        /// <summary>
        /// Test the property 'PrimaryRewardUnit'
        /// </summary>
        [Test]
        public void PrimaryRewardUnitTest()
        {
            // TODO unit test for the property 'PrimaryRewardUnit'
        }
        /// <summary>
        /// Test the property 'LastPaymentAmount'
        /// </summary>
        [Test]
        public void LastPaymentAmountTest()
        {
            // TODO unit test for the property 'LastPaymentAmount'
        }
        /// <summary>
        /// Test the property 'RemainingBalance'
        /// </summary>
        [Test]
        public void RemainingBalanceTest()
        {
            // TODO unit test for the property 'RemainingBalance'
        }
        /// <summary>
        /// Test the property 'UserClassification'
        /// </summary>
        [Test]
        public void UserClassificationTest()
        {
            // TODO unit test for the property 'UserClassification'
        }
        /// <summary>
        /// Test the property 'BankTransferCode'
        /// </summary>
        [Test]
        public void BankTransferCodeTest()
        {
            // TODO unit test for the property 'BankTransferCode'
        }
        /// <summary>
        /// Test the property 'ExpirationDate'
        /// </summary>
        [Test]
        public void ExpirationDateTest()
        {
            // TODO unit test for the property 'ExpirationDate'
        }
        /// <summary>
        /// Test the property 'Coverage'
        /// </summary>
        [Test]
        public void CoverageTest()
        {
            // TODO unit test for the property 'Coverage'
        }
        /// <summary>
        /// Test the property 'CashApr'
        /// </summary>
        [Test]
        public void CashAprTest()
        {
            // TODO unit test for the property 'CashApr'
        }
        /// <summary>
        /// Test the property 'AutoRefresh'
        /// </summary>
        [Test]
        public void AutoRefreshTest()
        {
            // TODO unit test for the property 'AutoRefresh'
        }
        /// <summary>
        /// Test the property 'OauthMigrationStatus'
        /// </summary>
        [Test]
        public void OauthMigrationStatusTest()
        {
            // TODO unit test for the property 'OauthMigrationStatus'
        }
        /// <summary>
        /// Test the property 'DisplayedName'
        /// </summary>
        [Test]
        public void DisplayedNameTest()
        {
            // TODO unit test for the property 'DisplayedName'
        }
        /// <summary>
        /// Test the property 'FullAccountNumberList'
        /// </summary>
        [Test]
        public void FullAccountNumberListTest()
        {
            // TODO unit test for the property 'FullAccountNumberList'
        }
        /// <summary>
        /// Test the property 'AmountDue'
        /// </summary>
        [Test]
        public void AmountDueTest()
        {
            // TODO unit test for the property 'AmountDue'
        }
        /// <summary>
        /// Test the property 'CurrentLevel'
        /// </summary>
        [Test]
        public void CurrentLevelTest()
        {
            // TODO unit test for the property 'CurrentLevel'
        }
        /// <summary>
        /// Test the property 'OriginalLoanAmount'
        /// </summary>
        [Test]
        public void OriginalLoanAmountTest()
        {
            // TODO unit test for the property 'OriginalLoanAmount'
        }
        /// <summary>
        /// Test the property 'PolicyToDate'
        /// </summary>
        [Test]
        public void PolicyToDateTest()
        {
            // TODO unit test for the property 'PolicyToDate'
        }
        /// <summary>
        /// Test the property 'LoanPayoffDetails'
        /// </summary>
        [Test]
        public void LoanPayoffDetailsTest()
        {
            // TODO unit test for the property 'LoanPayoffDetails'
        }
        /// <summary>
        /// Test the property 'PaymentProfile'
        /// </summary>
        [Test]
        public void PaymentProfileTest()
        {
            // TODO unit test for the property 'PaymentProfile'
        }
        /// <summary>
        /// Test the property 'CONTAINER'
        /// </summary>
        [Test]
        public void CONTAINERTest()
        {
            // TODO unit test for the property 'CONTAINER'
        }
        /// <summary>
        /// Test the property 'LastEmployeeContributionDate'
        /// </summary>
        [Test]
        public void LastEmployeeContributionDateTest()
        {
            // TODO unit test for the property 'LastEmployeeContributionDate'
        }
        /// <summary>
        /// Test the property 'LastPayment'
        /// </summary>
        [Test]
        public void LastPaymentTest()
        {
            // TODO unit test for the property 'LastPayment'
        }
        /// <summary>
        /// Test the property 'RecurringPayment'
        /// </summary>
        [Test]
        public void RecurringPaymentTest()
        {
            // TODO unit test for the property 'RecurringPayment'
        }

    }

}
