/* 
 * Yodlee Core APIs
 *
 * This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. You can generate a client SDK for Python, Java, JavaScript, PHP, or other languages according to your development needs. For more details about the APIs, refer to <a href=\"https://developer.envestnet.com/resources/yodlee/yodlee-api-overview/docs\">Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API's description.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: developer@yodlee.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Statement
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StatementTests
    {
        // TODO uncomment below to declare an instance variable for Statement
        //private Statement instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Statement
            //instance = new Statement();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Statement
        /// </summary>
        [Test]
        public void StatementInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Statement
            //Assert.IsInstanceOfType<Statement> (instance, "variable 'instance' is a Statement");
        }


        /// <summary>
        /// Test the property 'Apr'
        /// </summary>
        [Test]
        public void AprTest()
        {
            // TODO unit test for the property 'Apr'
        }
        /// <summary>
        /// Test the property 'CashApr'
        /// </summary>
        [Test]
        public void CashAprTest()
        {
            // TODO unit test for the property 'CashApr'
        }
        /// <summary>
        /// Test the property 'BillingPeriodStart'
        /// </summary>
        [Test]
        public void BillingPeriodStartTest()
        {
            // TODO unit test for the property 'BillingPeriodStart'
        }
        /// <summary>
        /// Test the property 'DueDate'
        /// </summary>
        [Test]
        public void DueDateTest()
        {
            // TODO unit test for the property 'DueDate'
        }
        /// <summary>
        /// Test the property 'InterestAmount'
        /// </summary>
        [Test]
        public void InterestAmountTest()
        {
            // TODO unit test for the property 'InterestAmount'
        }
        /// <summary>
        /// Test the property 'StatementDate'
        /// </summary>
        [Test]
        public void StatementDateTest()
        {
            // TODO unit test for the property 'StatementDate'
        }
        /// <summary>
        /// Test the property 'CashAdvance'
        /// </summary>
        [Test]
        public void CashAdvanceTest()
        {
            // TODO unit test for the property 'CashAdvance'
        }
        /// <summary>
        /// Test the property 'BillingPeriodEnd'
        /// </summary>
        [Test]
        public void BillingPeriodEndTest()
        {
            // TODO unit test for the property 'BillingPeriodEnd'
        }
        /// <summary>
        /// Test the property 'PrincipalAmount'
        /// </summary>
        [Test]
        public void PrincipalAmountTest()
        {
            // TODO unit test for the property 'PrincipalAmount'
        }
        /// <summary>
        /// Test the property 'LoanBalance'
        /// </summary>
        [Test]
        public void LoanBalanceTest()
        {
            // TODO unit test for the property 'LoanBalance'
        }
        /// <summary>
        /// Test the property 'AmountDue'
        /// </summary>
        [Test]
        public void AmountDueTest()
        {
            // TODO unit test for the property 'AmountDue'
        }
        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Test]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'LastUpdated'
        /// </summary>
        [Test]
        public void LastUpdatedTest()
        {
            // TODO unit test for the property 'LastUpdated'
        }
        /// <summary>
        /// Test the property 'IsLatest'
        /// </summary>
        [Test]
        public void IsLatestTest()
        {
            // TODO unit test for the property 'IsLatest'
        }
        /// <summary>
        /// Test the property 'MinimumPayment'
        /// </summary>
        [Test]
        public void MinimumPaymentTest()
        {
            // TODO unit test for the property 'MinimumPayment'
        }
        /// <summary>
        /// Test the property 'LastPaymentDate'
        /// </summary>
        [Test]
        public void LastPaymentDateTest()
        {
            // TODO unit test for the property 'LastPaymentDate'
        }
        /// <summary>
        /// Test the property 'LastPaymentAmount'
        /// </summary>
        [Test]
        public void LastPaymentAmountTest()
        {
            // TODO unit test for the property 'LastPaymentAmount'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'NewCharges'
        /// </summary>
        [Test]
        public void NewChargesTest()
        {
            // TODO unit test for the property 'NewCharges'
        }

    }

}
