/* 
 * Yodlee Core APIs
 *
 * This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. You can generate a client SDK for Python, Java, JavaScript, PHP, or other languages according to your development needs. For more details about the APIs, refer to <a href=\"https://developer.envestnet.com/resources/yodlee/yodlee-api-overview/docs\">Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API's description.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: developer@yodlee.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UpdateTransaction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UpdateTransactionTests
    {
        // TODO uncomment below to declare an instance variable for UpdateTransaction
        //private UpdateTransaction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateTransaction
            //instance = new UpdateTransaction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateTransaction
        /// </summary>
        [Test]
        public void UpdateTransactionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateTransaction
            //Assert.IsInstanceOfType<UpdateTransaction> (instance, "variable 'instance' is a UpdateTransaction");
        }


        /// <summary>
        /// Test the property 'CategorySource'
        /// </summary>
        [Test]
        public void CategorySourceTest()
        {
            // TODO unit test for the property 'CategorySource'
        }
        /// <summary>
        /// Test the property 'Container'
        /// </summary>
        [Test]
        public void ContainerTest()
        {
            // TODO unit test for the property 'Container'
        }
        /// <summary>
        /// Test the property 'IsPhysical'
        /// </summary>
        [Test]
        public void IsPhysicalTest()
        {
            // TODO unit test for the property 'IsPhysical'
        }
        /// <summary>
        /// Test the property 'DetailCategoryId'
        /// </summary>
        [Test]
        public void DetailCategoryIdTest()
        {
            // TODO unit test for the property 'DetailCategoryId'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Memo'
        /// </summary>
        [Test]
        public void MemoTest()
        {
            // TODO unit test for the property 'Memo'
        }
        /// <summary>
        /// Test the property 'MerchantType'
        /// </summary>
        [Test]
        public void MerchantTypeTest()
        {
            // TODO unit test for the property 'MerchantType'
        }
        /// <summary>
        /// Test the property 'CategoryId'
        /// </summary>
        [Test]
        public void CategoryIdTest()
        {
            // TODO unit test for the property 'CategoryId'
        }

    }

}
