/*
 * Yodlee Core APIs
 * This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. You can generate a client SDK for Python, Java, JavaScript, PHP, or other languages according to your development needs. For more details about the APIs, refer to <a href=\"https://developer.envestnet.com/resources/yodlee/yodlee-api-overview/docs\">Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API's description.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: developer@yodlee.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.YodleeCoreApis);
  }
}(this, function(expect, YodleeCoreApis) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new YodleeCoreApis.TransactionsApi();
  });

  describe('(package)', function() {
    describe('TransactionsApi', function() {
      describe('createOrRunTransactionCategorizationRules', function() {
        it('should call createOrRunTransactionCategorizationRules successfully', function(done) {
          // TODO: uncomment, update parameter values for createOrRunTransactionCategorizationRules call
          /*
          var opts = {};

          instance.createOrRunTransactionCategorizationRules(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createTransactionCategory', function() {
        it('should call createTransactionCategory successfully', function(done) {
          // TODO: uncomment, update parameter values for createTransactionCategory call
          /*

          instance.createTransactionCategory(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteTransactionCategorizationRule', function() {
        it('should call deleteTransactionCategorizationRule successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteTransactionCategorizationRule call
          /*

          instance.deleteTransactionCategorizationRule(ruleId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteTransactionCategory', function() {
        it('should call deleteTransactionCategory successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteTransactionCategory call
          /*

          instance.deleteTransactionCategory(categoryId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTransactionCategories', function() {
        it('should call getTransactionCategories successfully', function(done) {
          // TODO: uncomment getTransactionCategories call and complete the assertions
          /*

          instance.getTransactionCategories(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(YodleeCoreApis.TransactionCategoryResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTransactionCategorizationRules', function() {
        it('should call getTransactionCategorizationRules successfully', function(done) {
          // TODO: uncomment getTransactionCategorizationRules call and complete the assertions
          /*

          instance.getTransactionCategorizationRules(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(YodleeCoreApis.TransactionCategorizationRuleResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTransactionCategorizationRulesDeprecated', function() {
        it('should call getTransactionCategorizationRulesDeprecated successfully', function(done) {
          // TODO: uncomment getTransactionCategorizationRulesDeprecated call and complete the assertions
          /*

          instance.getTransactionCategorizationRulesDeprecated(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(YodleeCoreApis.TransactionCategorizationRule);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTransactions', function() {
        it('should call getTransactions successfully', function(done) {
          // TODO: uncomment, update parameter values for getTransactions call and complete the assertions
          /*
          var opts = {};

          instance.getTransactions(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(YodleeCoreApis.TransactionResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTransactionsCount', function() {
        it('should call getTransactionsCount successfully', function(done) {
          // TODO: uncomment, update parameter values for getTransactionsCount call and complete the assertions
          /*
          var opts = {};

          instance.getTransactionsCount(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(YodleeCoreApis.TransactionCountResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('runTransactionCategorizationRule', function() {
        it('should call runTransactionCategorizationRule successfully', function(done) {
          // TODO: uncomment, update parameter values for runTransactionCategorizationRule call
          /*

          instance.runTransactionCategorizationRule(action, ruleId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateTransaction', function() {
        it('should call updateTransaction successfully', function(done) {
          // TODO: uncomment, update parameter values for updateTransaction call
          /*

          instance.updateTransaction(body, transactionId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateTransactionCategorizationRule', function() {
        it('should call updateTransactionCategorizationRule successfully', function(done) {
          // TODO: uncomment, update parameter values for updateTransactionCategorizationRule call
          /*

          instance.updateTransactionCategorizationRule(body, ruleId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateTransactionCategory', function() {
        it('should call updateTransactionCategory successfully', function(done) {
          // TODO: uncomment, update parameter values for updateTransactionCategory call
          /*

          instance.updateTransactionCategory(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
