/* 
 * Yodlee Core APIs
 *
 * This file describes the Yodlee Platform APIs using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. You can generate a client SDK for Python, Java, JavaScript, PHP, or other languages according to your development needs. For more details about the APIs, refer to <a href=\"https://developer.envestnet.com/resources/yodlee/yodlee-api-overview/docs\">Yodlee API v1.1 - Overview</a>.<br><br>You will have to set the header before making the API call. The following headers apply to all the APIs:<ul><li>Authorization: This header holds the access token</li> <li> Api-Version: 1.1</li></ul><b>Note</b>: If there are any API-specific headers, they are mentioned explicitly in the respective API's description.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: developer@yodlee.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// TransactionDays
    /// </summary>
    [DataContract]
        public partial class TransactionDays :  IEquatable<TransactionDays>, IValidatableObject
    {
        /// <summary>
        /// Defines FullAccountNumberFields
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum FullAccountNumberFieldsEnum
        {
            /// <summary>
            /// Enum PaymentAccountNumber for value: paymentAccountNumber
            /// </summary>
            [EnumMember(Value = "paymentAccountNumber")]
            PaymentAccountNumber = 1,
            /// <summary>
            /// Enum UnmaskedAccountNumber for value: unmaskedAccountNumber
            /// </summary>
            [EnumMember(Value = "unmaskedAccountNumber")]
            UnmaskedAccountNumber = 2        }
        /// <summary>
        /// Gets or Sets FullAccountNumberFields
        /// </summary>
        [DataMember(Name="fullAccountNumberFields", EmitDefaultValue=false)]
        public List<FullAccountNumberFieldsEnum> FullAccountNumberFields { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionDays" /> class.
        /// </summary>
        /// <param name="fullAccountNumberFields">fullAccountNumberFields.</param>
        /// <param name="numberOfTransactionDays">numberOfTransactionDays.</param>
        public TransactionDays(List<FullAccountNumberFieldsEnum> fullAccountNumberFields = default(List<FullAccountNumberFieldsEnum>), int? numberOfTransactionDays = default(int?))
        {
            this.FullAccountNumberFields = fullAccountNumberFields;
            this.NumberOfTransactionDays = numberOfTransactionDays;
        }
        

        /// <summary>
        /// Gets or Sets NumberOfTransactionDays
        /// </summary>
        [DataMember(Name="numberOfTransactionDays", EmitDefaultValue=false)]
        public int? NumberOfTransactionDays { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransactionDays {\n");
            sb.Append("  FullAccountNumberFields: ").Append(FullAccountNumberFields).Append("\n");
            sb.Append("  NumberOfTransactionDays: ").Append(NumberOfTransactionDays).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TransactionDays);
        }

        /// <summary>
        /// Returns true if TransactionDays instances are equal
        /// </summary>
        /// <param name="input">Instance of TransactionDays to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransactionDays input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FullAccountNumberFields == input.FullAccountNumberFields ||
                    this.FullAccountNumberFields != null &&
                    input.FullAccountNumberFields != null &&
                    this.FullAccountNumberFields.SequenceEqual(input.FullAccountNumberFields)
                ) && 
                (
                    this.NumberOfTransactionDays == input.NumberOfTransactionDays ||
                    (this.NumberOfTransactionDays != null &&
                    this.NumberOfTransactionDays.Equals(input.NumberOfTransactionDays))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FullAccountNumberFields != null)
                    hashCode = hashCode * 59 + this.FullAccountNumberFields.GetHashCode();
                if (this.NumberOfTransactionDays != null)
                    hashCode = hashCode * 59 + this.NumberOfTransactionDays.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
